name: dbt-checkpoint

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  path-filter:
    uses: ./.github/workflows/wc-path-filter.yaml
    permissions:
      id-token: write
      pull-requests: write
      contents: write

  dbt-checkpoint:
    runs-on: ubuntu-latest
    env:
      ACCOUNT: ${{ vars.ACCOUNT }}
      DATABASE: ${{ vars.DATABASE }}
      SCHEMA: ${{ vars.SCHEMA }}
      USER: ${{ vars.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      ROLE: ${{ vars.ROLE }}
      WAREHOUSE: ${{ vars.WAREHOUSE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Get all changed yaml files
        id: changed-yaml-files
        uses: tj-actions/changed-files@0c6f2ac4885216b1830ecbcc3573209980c97716 # v41
        with:
          files: |
            *.yml
          base_sha: ${{ inputs.base_ref }}


      - name: Run dbt checkpoint
        run: |
          pip install dbt-core = "==1.8.0"
          pip install dbt-bigquery = "==1.8.0"
          pip install precommit

      - name: Run dbt checkpoint
        run: |
          pre-commit run