name: dbt-table-doc-check
on: push
jobs:
  check_doc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install core tools
        run: |
          pip install "dbt-core==1.8" "dbt-bigquery==1.8" "pre-commit"

      - name: Parse dbt project
        run: |
          cd dbt_prj
          dbt parse

      # テーブル description が無ければ exit 1
      - name: Enforce table descriptions
        run: |
          pre-commit run
